### ISSUE TITLE
ModuleNotFound in model linearization

### ISSUE THREAD

**Issue by PT-Traviresta** [OpenModelica/OMPython#196] opened 2024-02-28 06:41 UTC
https://github.com/OpenModelica/OMPython/blob/bd17a664a79a64f55292598cf2e13d1469289c41/OMPython/__init__.py#L1751

I ran a script file and had the problem of ModuleNotFound when importing `linearized_model`.

My solution is to modify `__init__.py` and append the analysis folder to `sys.path`

```python
sys.path.append(os.path.dirname(linearFile))
from linearized_model import linearized_model
```

**Comment by arun3688** [comment] 2024-02-28 09:03
@PT-Traviresta usually it should not be problem because the session is running in the directory where the linearized file is created

**Comment by PT-Traviresta** [comment] 2024-02-29 00:53
@arun3688 

If I run the script line-by-line in the interactive mode, there's no problem. But if I run it in the script mode, the error occur.

My friend also faced the same problem.

**Comment by arun3688** [comment] 2024-02-29 10:12
@PT-Traviresta the issue is fixed with this commit https://github.com/OpenModelica/OMPython/commit/59ff73b96cf6002049a8191039e9a8256a93ac74, Thanks for the contribution, i will close this issue, please open the issue in case you face any problem

**Closed by arun3688** 2024-02-29 10:12 UTC

**Comment by martinscripts** [comment] 2025-08-20 08:11
Hey @syntron, 

I am on v3.6.0 and python 3.13.2 and in [OMPython's pyproject.toml](https://github.com/OpenModelica/OMPython/blob/master/pyproject.toml) it says `version = "3.6.0"`, so that seems to be the latest one? 

Which version should I install instead? 

here my mwe: 

```
from OMPython import OMCSessionZMQ
from OMPython import ModelicaSystem
omc = OMCSessionZMQ()
model_path=omc.sendExpression("getInstallationDirectoryPath()") + "/share/doc/omc/testmodels/"

mod1 = ModelicaSystem(model_path + "BouncingBall.mo","BouncingBall")
mod1.linearize()
```
 
output: 

```
SyntaxError                               Traceback (most recent call last)
File c:\Users\mfranke\Documents\projects\general_python\.venv\Lib\site-packages\OMPython\__init__.py:1776, in ModelicaSystem.linearize(self, lintime, simflags)
   1773 try:
   1774     ## do not add the linearfile directory to path, as multiple execution of linearization will always use the first added path, instead execute the file
   1775     ## https://github.com/OpenModelica/OMPython/issues/196
-> [1776](file:///C:/Users/mfranke/Documents/projects/general_python/.venv/Lib/site-packages/OMPython/__init__.py:1776)     module = importlib.machinery.SourceFileLoader("linearized_model", linearFile).load_module()
   1777     result = module.linearized_model()

File <frozen importlib._bootstrap_external>:680, in _check_name_wrapper(self, name, *args, **kwargs)

File <frozen importlib._bootstrap_external>:1207, in load_module(self, fullname)

File <frozen importlib._bootstrap_external>:1031, in load_module(self, fullname)

File <frozen importlib._bootstrap>:537, in _load_module_shim(self, fullname)

File <frozen importlib._bootstrap>:966, in _load(spec)

File <frozen importlib._bootstrap>:935, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:1022, in exec_module(self, module)

File <frozen importlib._bootstrap_external>:1160, in get_code(self, fullname)
...
-> [1786](file:///C:/Users/mfranke/Documents/projects/general_python/.venv/Lib/site-packages/OMPython/__init__.py:1786)         raise Exception("ModuleNotFoundError: No module named 'linearized_model'")
   1787 else:
   1788     errormsg = self.getconn.sendExpression("getErrorString()")

Exception: ModuleNotFoundError: No module named 'linearized_model'
```

**Comment by martinscripts** [comment] 2025-08-20 11:00
ok, thanks. 

I did `pip install git+https://github.com/OpenModelica/OMPython.git` now, which I assume should do the same? 

With the same mwe from above, I now get 

```
ModelicaSystemError                       Traceback (most recent call last)
Cell In[1], [line 7](vscode-notebook-cell:?execution_count=1&line=7)
      4 model_path=omc.sendExpression("getInstallationDirectoryPath()") + "/share/doc/omc/testmodels/"
      6 mod1 = ModelicaSystem(model_path + "BouncingBall.mo","BouncingBall")
----> [7](vscode-notebook-cell:?execution_count=1&line=7) mod1.linearize()
      9 # plt.plot([1,2,3])
     10 # plt.savefig('test_before.png')
     11 # plt.show()
   (...)     15 # plt.savefig('test_after.png')
     16 # plt.show()

File c:\Users\mfranke\Documents\projects\general_python\.venv\Lib\site-packages\OMPython\ModelicaSystem.py:1672, in ModelicaSystem.linearize(self, lintime, simflags, simargs, timeout)
   1669 linear_file = self.getWorkDirectory() / "linearized_model.py"
   1670 linear_file.unlink(missing_ok=True)
-> [1672](file:///C:/Users/mfranke/Documents/projects/general_python/.venv/Lib/site-packages/OMPython/ModelicaSystem.py:1672) returncode = om_cmd.run()
   1673 if returncode != 0:
   1674     raise ModelicaSystemError(f"Linearize failed with return code: {returncode}")

File c:\Users\mfranke\Documents\projects\general_python\.venv\Lib\site-packages\OMPython\ModelicaSystem.py:279, in ModelicaSystemCmd.run(self)
    277 path_bat = self._runpath / f"{self._model_name}.bat"
    278 if not path_bat.exists():
--> [279](file:///C:/Users/mfranke/Documents/projects/general_python/.venv/Lib/site-packages/OMPython/ModelicaSystem.py:279)     raise ModelicaSystemError("Batch file (*.bat) does not exist " + str(path_bat))
    281 with open(file=path_bat, mode='r', encoding='utf-8') as fh:
    282     for line in fh:

ModelicaSystemError: Batch file (*.bat) does not exist C:\Users\mfranke\AppData\Local\Temp\tmph422rspr\BouncingBall.bat
```
