### ISSUE TITLE
Unable to load files containing annotation

### ISSUE THREAD

**Issue by PatronusCoder** [OpenModelica/OMPython#81] opened 2019-01-30 13:29 UTC
I am using OpenModelica version v1.13.1, jupyter python notebook and OMPython. I have developed a package in OMEditor as follows:

```
package NewPackage
  model firstPackageModel
  input Real val;
  equation

  end firstPackageModel;

  model WheelVelocity
  
  parameter Real R = 0.1 "Radius of the wheel";
  parameter Real L = 0.35 "Distance between center of the wheels";
  
  input Real V;
  input Real w;
  
  Real w_l;
  Real w_r;
  
  equation
    
    V = R*(w_r+w_l)/2;
    w = R*(w_r-w_l)/L;

  end WheelVelocity;
  annotation(
    uses(Modelica(version = "3.2.2")));
end NewPackage;

```
I am trying to load this model in a python file using ModelicaSystem class of OMPython library. I have checked the current working directory of my python notebook to be the same as that of this package. When I run:
`mod = ModelicaSystem("NewPackage.mo","NewPackage.WheelVelocity")`
I get following error:

```
2019-01-30 14:22:51,136 - OMPython - INFO - OMC Server is up and running at file:///C:/Users/MyPC/AppData/Local/Temp/openmodelica.port.df50f7eccef8467b8bc5dc35b17aae04 pid=15672 
loadFile Error: Notification: Automatically loaded package Modelica 3.2.2 due to uses annotation.
Notification: Automatically loaded package Complex 3.2.2 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 3.2.2 due to uses annotation.
```
But in the above model code, if I comment the annotation part, then there is no issue. I am unable to understand what seems to be the problem.

**Comment by adeas31** [comment] 2019-01-30 13:55
The message you see is also not an error. The file is loaded successfully.
The problem is it says `loadFile Error` which is misleading and should be fixed.

**Comment by arun3688** [comment] 2019-01-30 14:12
There is error as stated by the user, because all the API don't have any datas, the loadFile Fails in the ModelicaSystem() if the model has annotations, but it works fine with OMCSessionZMQ, i will look into the problem

**Comment by arun3688** [comment] 2019-01-30 14:54
@PatronusCoder  This error is fixed in this commit  
https://github.com/OpenModelica/OMPython/commit/27c8b413c810c82afb3ee40f016dfd785aa3ea11

**Comment by PatronusCoder** [comment] 2019-01-30 15:53
[#@arun3688] Thanks for the quick response. Please resolve the comment in the code for this commit. Also, how would I update the library on my system with these changes? Would simply editing it in the __init__.py file same as you did suffice?

**Comment by PatronusCoder** [comment] 2019-01-30 16:07
@arun3688 Thanks for quick response. How do I update the library in my system now with these changes? Would adding the same code to the "__init__.py" file in path "C:\OpenModelica1.13.164bit\share\omc\scripts\PythonInterface\OMPython" be enough?

**Comment by arun3688** [comment] 2019-01-30 16:31
@PatronusCoder , You should use
>> git pull 

and then >> python -m pip install -U .

**Comment by arun3688** [comment] 2019-01-30 16:33
@PatronusCoder , Adding the same code to init.py also works, but you can clone the OMPython repository and do the  >> python -m pip install -U .  so that when we do a fix you can use git pull and then have the latest changes

**Comment by PatronusCoder** [comment] 2019-01-30 20:15
But how does the above change help with loading models which contain annotations?

**Comment by arun3688** [comment] 2019-01-30 20:49
@PatronusCoder , The above changes  just eliminates the loadFile error which you got previously because it is not an error, it is just a notification that the model loads those annotation along with the model. So with the above changes you can load the models with and without annotation

**Closed** 2019-01-31 07:52 UTC
