### ISSUE TITLE
Custom Build Directory

### ISSUE THREAD

**Issue by kiroorooki** [OpenModelica/OMPython#204] opened 2024-03-24 23:55 UTC
Hey, I need to build my model in a specific folder for my program.

I have no clue if this functionality already exists but I've modified OMPython for my purpose.

Can someone tell me if there's a proper way and if there isn't, can we add this functionality to OMPython?
Many thanks!

Modification:
-Added "customBuildDirectory=None" as an argument for ModelicaSystem

-Added the following ModelicaSystem init:
```
if customBuildDirectory is not None:
    exp="".join(["cd(","\"",customBuildDirectory,"\"",")"])
    self.getconn.sendExpression(exp)

```

**Comment by arun3688** [comment] 2024-03-25 10:52
@kiroorooki the issue is fixed with this commit https://github.com/OpenModelica/OMPython/commit/bdd04a37ee99a9c110b5df87b771fa1f7d0205ca, please update your pip package with the following command

`python -m pip install -U https://github.com/OpenModelica/OMPython/archive/master.zip
`

**Closed** 2024-03-25 14:44 UTC
