### ISSUE TITLE
'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by NuQuantro** [OpenModelica/OMPython#137] opened 2021-05-05 10:35 UTC
I am trying to load a file in Python but getting this error and I have tried to solve this issue as suggested here to _int_.py file
 [def _get_element_text(self, element):
        """
        Return the textual content of the element and its children
        """
        text = ''
        if element.text is not None:
            text += element.text
        for child in element.getchildren():
         for child in element:
            text += self._get_element_text(child)
        if element.tail is not None:
            text += element.tail
        return text](url)
But getting the same issue and not be able to do anything. My code is following:
[import matplotlib.pyplot as plt  
import OMPython
from OMPython import OMCSessionZMQ
from OMPython import ModelicaSystem
omc = OMCSessionZMQ()
mod = ModelicaSystem("Li_ionBattery.mo", "Li_ionBattery.TestBench.VaryingCurrent")
Li_simulation = mod.getSimulationOptions()
mod.setSimulationOptions(["stopTime=2000", "stepSize=50"])
variables_vary = mod.getQuantities()
Parameters_vary = mod.getParameters() 
continous_vary = mod.getContinuous() 
mod.setParameters(["nMC_Data.Q_nom=11", "nMC_Data.Rs=0.0003"])
mod.simulate()](url)

**Comment by arun3688** [comment] 2021-05-06 11:09
@NuQuantro The issue is fixed with https://github.com/OpenModelica/OMPython/commit/59ef1e3ea25ccc5b60496622b0415df36316d3c0, but this fix is not available with pip installation yet, I guess you could clone the master and build it from the setup file `python setup.py install`

**Comment by adeas31** [comment] 2021-05-06 16:45
@arun3688 we should make a new version.

**Comment by NuQuantro** [comment] 2021-05-10 08:40
Yes, it worked. Thanks @arun3688

**Comment by arun3688** [comment] 2021-05-10 08:53
@adeas31 Yes do you have access to the pip repository ?, i think only martin has it

**Comment by adeas31** [comment] 2021-05-11 13:01
Accept the invitation and you upload new releases.

**Closed** 2021-05-11 13:01 UTC
